### ISSUE TITLE
Crash due to missing notification access on Android 10

### ISSUE THREAD

**Issue by markusEmm123** [Belkaar/ZeroNavBridge#4]
After getting BT to work, here comes the next one ;)

When i enable one of the three "use notification" sliders, the app immediately crashes.

In debug mode I see that it throws an exception SettingNotFoundException (for the setting name "enabled_notification_listeners") when calling
android.provider.Settings.Secure.getString(context.contentResolver, "enabled_notification_listeners"), in line 24 in NavNotificationListener.kt.

If i understand your code correctly, I should be redirected to the permission settings for notification access instead of getting that exception.
For some reason this does not work on my Mate 20 pro/Huawei/Android 10.

The error persists if i try to restart the app. 
I need to delete the cache/settings or the app (if I don't manually grant the permission in the system seetings).

Once I enable the permission for notification access in my system settings manually, i can select the slider without a crash.

**Comment by Belkaar** [comment]
I'll have a look if I can reproduce this

**Comment by Belkaar** [comment]
Commit 913acfd56fe96dc1eca6ba042d3bbd3274e8464e should resolve this.

**Comment by markusEmm123** [comment]
Now it crashes in line 40, with

> Unable to start activity ComponentInfo{team.burkart.zero.navbridge/team.burkart.zero.navbridge.MainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.NOTIFICATION_LISTENER_DETAIL_SETTINGS (has extras) }

**Comment by Belkaar** [comment]
Should work now. Optimistic release v1.5 :-)

**Comment by markusEmm123** [comment]
Does not crash anymore. Still does not open the settings, but at least shows a overlay message "Enable notification access for this function".
Works for me ;)
